name: "Two layers MLP"
model:
  _target_: models.MLPModel
  num_layers: 2
  hidden_dim: 8
optimizer:
  _target_: torch.optim.Adam
  lr: 0.1
criterion:
  _target_: torch.nn.MSELoss
dataset:
  _target_: dataset.MoleculeDataset
  filepath: "data.csv"
batch_size: 128
num_epochs: 5
save_path: "2l_mlp.pt"
early_stop: 10
split_ratios: [0.6, 0.3, 0.1]
random_state: 42
collate_fn:
  _target_: collate_fn.hetero_collate_fn
image_path: "2l_mlp.png"
