name: "Hetero GNN with center and rotation transform and GATConv"
model:
  _target_: models.HeteroGNN
  conv_type:
    _target_: models.GAT
    _partial_: True
  hidden_channels: 16
  out_channels: 8
  head_dim: 4
  heads: 1
optimizer:
  _target_: torch.optim.Adam
criterion:
  _target_: torch.nn.MSELoss
dataset:
  _target_: dataset.MoleculeDataset
  filepath: "data.csv"
  train_transform:
    _target_: transforms.Compose
    transforms:
      - _target_: transforms.Center
      - _target_: transforms.Rotation
  eval_transform:
    _target_: transforms.Center
batch_size: 128
num_epochs: 30
save_path: "hetero_gnn_center_roation_gat.pt"
early_stop: 10
split_ratios: [0.6, 0.3, 0.1]
random_state: 42
collate_fn:
  _target_: collate_fn.hetero_collate_fn
image_path: "hetero_gnn_center_rotation_gat.png"
